# Generated by Django 4.2.2 on 2023-06-16 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
