# Generated by Django 4.2.2 on 2023-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='email_list',
            field=models.TextField(blank=True, help_text='Enter email addresses separated by commas', null=True),
        ),
    ]
