# Generated by Django 4.2.2 on 2023-06-17 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_email_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='song',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='email_list',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
