# Generated by Django 4.2.2 on 2023-06-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_uploaded_at_alter_song_access_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='access_level',
            new_name='privacy_access',
        ),
        migrations.AlterField(
            model_name='song',
            name='email_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
