# Generated by Django 4.2.2 on 2023-06-17 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_rename_access_level_song_privacy_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='email_list',
        ),
        migrations.AddField(
            model_name='song',
            name='allowed_emails',
            field=models.ManyToManyField(blank=True, related_name='allowed_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='privacy_access',
            field=models.CharField(max_length=20),
        ),
    ]
